name: iosApp
options:
  bundleIdPrefix: com.ifochka
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ifochka.jufk
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_NAME: JUFK
        FRAMEWORK_SEARCH_PATHS:
          - "$(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework"
          - "$(SRCROOT)/../composeApp/build/bin/iosArm64/debugFramework"
          - "$(SRCROOT)/../composeApp/build/bin/iosX64/debugFramework"
        OTHER_LDFLAGS:
          - "-framework"
          - "ComposeApp"
      configs:
        Debug:
          FRAMEWORK_SEARCH_PATHS:
            - "$(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework"
            - "$(SRCROOT)/../composeApp/build/bin/iosArm64/debugFramework"
        Release:
          FRAMEWORK_SEARCH_PATHS:
            - "$(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/releaseFramework"
            - "$(SRCROOT)/../composeApp/build/bin/iosArm64/releaseFramework"
    dependencies: []
    preBuildScripts:
      - name: "Compile Kotlin Framework"
        script: |
          cd "$SRCROOT/.."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    archive:
      config: Release
    shared: true
